name: fastshare
description: "Offline file sharing app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.0
  shared_preferences: ^2.5.4
  path_provider: ^2.1.3
  mobile_scanner: ^5.1.0
  file_picker: ^8.0.6
  url_launcher: ^6.2.6
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  go_router: ^14.2.0
  camera: ^0.11.0+1
  uuid: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  crypto: ^3.0.5
  archive: ^3.6.1
  flutter_foreground_task: ^6.1.2
  wakelock_plus: ^1.2.5
  bonsoir: ^6.0.1
  network_info_plus: ^5.0.3
  android_intent_plus: ^5.1.0
  device_info_plus: ^10.1.0
  clipboard_watcher: ^0.2.0
  fl_chart: ^0.66.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/fastshare_icon.png
  adaptive_icon_background: "#0F3D33"
  adaptive_icon_foreground: assets/icon/fastshare_icon.png

flutter_native_splash:
  color: "#0F3D33"
  image: assets/icon/fastshare_icon.png
  android: true
  ios: true
  android_12:
    color: "#0F3D33"
    icon_background_color: "#0F3D33"
    image: assets/icon/fastshare_icon.png
